# Generated by Django 3.2.5 on 2021-07-03 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Person`s name')),
            ],
            options={
                'verbose_name': 'Author',
                'db_table': 'author',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1000, verbose_name='Book title')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Date of creation')),
                ('description', models.TextField(max_length=100000, verbose_name='Book description')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.author')),
            ],
            options={
                'verbose_name': 'Book',
                'db_table': 'book',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=1000, verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Genre',
                'db_table': 'genre',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
                ('genre', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookshelf.genre')),
            ],
            options={
                'db_table': 'genre_book',
                'unique_together': {('book', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(through='bookshelf.BookGenre', to='bookshelf.Genre'),
        ),
    ]
